#include "/Engine/Public/Platform.ush"

Texture2D MainTexture : register(t0);
SamplerState MainSampler : register(s0);

struct VSOutput
{
	float4 Position : SV_POSITION;
	float2 UV : TEXCOORD0;
};


float4 MainPS(VSOutput Input) : SV_Target
{
	uint2 TexSize;
	MainTexture.GetDimensions(TexSize.x, TexSize.y);
	float2 samplePos = Input.UV * TexSize;
	float2 texPos1 = floor(samplePos - 0.5f) + 0.5f;
	float2 f = samplePos - texPos1;
    
    // Cubic B-spline weights
	float2 w0 = f * (-0.5f + f * (1.0f - 0.5f * f));
	float2 w1 = 1.0f + f * f * (-2.5f + 1.5f * f);
	float2 w2 = f * (0.5f + f * (2.0f - 1.5f * f));
	float2 w3 = f * f * (-0.5f + 0.5f * f);
    
	float2 w12 = w1 + w2;
	float2 offset12 = w2 / (w1 + w2);
    
	float2 texPos0 = texPos1 - 1;
	float2 texPos3 = texPos1 + 2;
	float2 texPos12 = texPos1 + offset12;
    
	texPos0 /= TexSize;
	texPos3 /= TexSize;
	texPos12 /= TexSize;
    
	float4 result = 0.0f;
    
	result += MainTexture.Sample(MainSampler, float2(texPos0.x, texPos0.y)) * w0.x * w0.y;
	result += MainTexture.Sample(MainSampler, float2(texPos12.x, texPos0.y)) * w12.x * w0.y;
	result += MainTexture.Sample(MainSampler, float2(texPos3.x, texPos0.y)) * w3.x * w0.y;
    
	result += MainTexture.Sample(MainSampler, float2(texPos0.x, texPos12.y)) * w0.x * w12.y;
	result += MainTexture.Sample(MainSampler, float2(texPos12.x, texPos12.y)) * w12.x * w12.y;
	result += MainTexture.Sample(MainSampler, float2(texPos3.x, texPos12.y)) * w3.x * w12.y;
    
	result += MainTexture.Sample(MainSampler, float2(texPos0.x, texPos3.y)) * w0.x * w3.y;
	result += MainTexture.Sample(MainSampler, float2(texPos12.x, texPos3.y)) * w12.x * w3.y;
	result += MainTexture.Sample(MainSampler, float2(texPos3.x, texPos3.y)) * w3.x * w3.y;
    
	return result;
}
