#include "/Engine/Public/Platform.ush"

RWTexture3D<half> RWNoiseTex;

uint3 TexSize;
int Octaves;
float Wrap;
int AxisCellCount;
float Amplitude;
int CellSize;
int Seed;

float hash(uint n)
{
    // integer hash copied from Hugo Elias
    n = (n << 13U) ^ n;
    n = n * (n * n * 15731U + 0x789221U) + 0x1376312589U;
    return float(n & uint(0x7fffffffU)) / float(0x7fffffff);
}


float Worley(float3 coord, int axisCellCount)
{
    int3 cellPos = floor(coord / CellSize);
    float3 fracPos = float3(coord / CellSize - cellPos);
    float dist = 1.0f;
    for (int z = -1; z <= 1; ++z)
    {
        for (int y = -1; y <= 1; ++y)
        {
            for (int x = -1; x <= 1; ++x)
            {
                int3 curCellPos = cellPos + int3(x, y, z);
                int cellIndex = curCellPos.x + axisCellCount * (curCellPos.y + curCellPos.z * axisCellCount);
                if (any(curCellPos == -1) || any(curCellPos == axisCellCount))
                {
                    int3 wrappedCellPos = fmod(curCellPos + axisCellCount, (int3) axisCellCount);
                    cellIndex = wrappedCellPos.x + axisCellCount * (wrappedCellPos.y + wrappedCellPos.z * axisCellCount);
                }
             
                float3 pointPos = curCellPos + float3(hash(Seed + cellIndex), hash(Seed + cellIndex * 2), hash(Seed + cellIndex * 3));
                dist = min(dist, distance(cellPos + fracPos, pointPos));
            }
        }
    }
    
    dist = sqrt(1.0f - dist * dist);
    dist *= dist * dist * dist * dist * dist;
    return dist;
}

[numthreads(8, 8, 8)]
void GenerateNoise(uint3 DTid : SV_DispatchThreadID)
{
    if (DTid.x >= TexSize.x || DTid.y >= TexSize.y || DTid.z >= TexSize.z)
        return;

    float3 pos = float3(DTid.xyz);
    float n = 0;
    float g = exp2(-1);
    float f = 1.0f;
    float a = 1.0f;
    
    for (int i = 0; i < Octaves; ++i)
    {
        float noise = Worley(pos * f + i * Wrap, AxisCellCount * f) * a;
        n += noise;
        f *= 2;
        a *= g;
    }
    n = saturate(n) * Amplitude;
    n = Amplitude - n;
    
    RWNoiseTex[DTid.xyz] = n ;
}
