#include "/Engine/Public/Platform.ush"

float Sharpness;
float2 ViewportSize;

Texture2D SceneTex;
Texture2D SmokeAlbedoTex;
Texture2D SmokeMaskTex;
SamplerState LinearClamp_Sampler;


void MainPS(
 	float4 SvPosition : SV_POSITION,
	out float4 OutColor : SV_Target0)
{
	float2 UV = SvPosition.xy / ViewportSize;
    
    // Get texture dimensions
	uint width, height;
	SceneTex.GetDimensions(width, height);
	float2 TexelSize = 1.0f / float2(width, height);
    
    // Sample textures
	float4 col = SceneTex.Sample(LinearClamp_Sampler, UV);
	float4 smokeAlbedo = SmokeAlbedoTex.Sample(LinearClamp_Sampler, UV);
	float smokeMask = 1 - saturate(SmokeMaskTex.Sample(LinearClamp_Sampler, UV).r);
	//float smokeMask = 0.5f;
    
    // Apply Sharpness (Laplacian filter)
	float neighbor = Sharpness * -1.0f;
	float center = Sharpness * 4.0f + 1.0f;
    
	float4 n = SmokeAlbedoTex.Sample(LinearClamp_Sampler, UV + TexelSize * float2(0, 1));
	float4 e = SmokeAlbedoTex.Sample(LinearClamp_Sampler, UV + TexelSize * float2(1, 0));
	float4 s = SmokeAlbedoTex.Sample(LinearClamp_Sampler, UV + TexelSize * float2(0, -1));
	float4 w = SmokeAlbedoTex.Sample(LinearClamp_Sampler, UV + TexelSize * float2(-1, 0));
    
	float4 sharpenedSmoke = n * neighbor + e * neighbor + smokeAlbedo * center + s * neighbor + w * neighbor;
    
	OutColor = lerp(col, saturate(sharpenedSmoke), 1.0f - smokeMask);
}
